platform :ios, '11.3'

target 'PIL' do

  
  source 'https://gitlab.linphone.org/BC/public/podspec.git'
  source 'https://github.com/CocoaPods/Specs.git'
  
  #//wip pod 'PhoneLib' ,:git => 'https://github.com/open-voip-alliance/iOSPhoneLib.git', 'branch' => 'main'
  pod 'PhoneLib', :path => '/Users/chris/projects/Vialer/iOS/ios-phone-lib'


  target 'PILTests' do
    # Pods for testing
  end
  
  target 'PILExampleApp' do
    pod 'PIL', :path => '/Users/chris/projects/Vialer/iOS/iOS-platform-integration-layer/PIL'
  end

end
