platform :ios, '11.3'

target 'PIL' do

  source 'https://gitlab.linphone.org/BC/public/podspec.git'
  source 'https://github.com/CocoaPods/Specs.git'
  use_frameworks!

  #//wip pod 'PhoneLib', :git => 'https://gitlab.wearespindle.com/vialer/mobile/voip/ios-phone-lib.git', 'branch' => 'main'
  pod 'iOSPhoneLib', :path => '/Users/chris/projects/Vialer/iOS/ios-phone-lib'
#  pod 'iOSPhoneLib', :git => 'https://gitlab.wearespindle.com/vialer/mobile/voip/ios-phone-lib.git'
  
  pod 'Swinject'

  target 'PILTests' do
    # Pods for testing
  end
  
  target 'PILExampleApp' do
    pod 'PIL', :path => '../PIL'
    pod 'AFNetworkActivityLogger'
    pod 'AFNetworking'
    pod 'SAMKeychain'
    pod 'QuickTableViewController'
    pod 'Alamofire', '~> 5.2'
  end

end
