platform :ios, '11.3'

target 'PILExampleApp' do
  
  source 'https://github.com/CocoaPods/Specs.git'
  
  pod 'PIL', :path => '/Users/chris/projects/Vialer/iOS/iOS-platform-integration-layer/PIL'
  pod 'PhoneLib', :path => '/Users/chris/projects/Vialer/iOS/ios-phone-lib'
  #//wip pod 'PhoneLib' ,:git => 'https://github.com/open-voip-alliance/iOSPhoneLib.git', 'branch' => 'main'
  
  target 'PILExampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PILExampleAppUITests' do
    # Pods for testing
  end

end
